version: '3.8'

services:
  db:
    image: postgres:15
    container_name: barber_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-1605}
      POSTGRES_DB: barbersystem
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    container_name: barber_backend
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD:-1605}@db:5432/barbersystem
    env_file:
      - ./backend/.env

volumes:
  postgres_data:
